---
- hosts: routers
  gather_facts: true
  connection: local

  tasks:
    - name: show run
      ios_command:
        commands:
          - show run
      register: config

    - name: save output to ./backups
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "~/Python/ansible/backups/show_run_{{ inventory_hostname }}.txt"
